# Generated by Django 4.1.3 on 2022-11-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpearl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oyster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('avatar_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pearl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('votes', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordpearl.oyster')),
            ],
        ),
        migrations.DeleteModel(
            name='Pearls',
        ),
        migrations.AddField(
            model_name='comment',
            name='pearl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordpearl.pearl'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordpearl.oyster'),
        ),
    ]
