# Generated by Django 4.1.3 on 2022-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpearl', '0002_comment_oyster_pearl_delete_pearls_comment_pearl_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pearl',
            name='body',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
