# Generated by Django 4.1.3 on 2022-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpearl', '0004_oyster_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pearl',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
