# Generated by Django 4.1.3 on 2022-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpearl', '0007_pearl_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pearl',
            name='points',
        ),
        migrations.AddField(
            model_name='oyster',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
